[project]
name = "reverse-proxy"
version = "0.1.0"
description = "Simple HTTP Reverse Proxy using Starlette and HTTPX"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
  "starlette",
  "httpx",
  "uvicorn"
]